openapi: 3.0.0
info:
  title: Example OpenApi 3 spec
  description: Has server variables
  version: 0.1.0
servers:
  - url:  https://test.com:{portVariable}/{pathVariable}
    description: relative server url
    variables:
      portVariable:
        enum: 
          - '1234'
          - '5678'
        default: '1234'
        description: variable at end of server path, like port number
      pathVariable:
        enum: 
          - 'defaultPathVariable'
          - 'nonDefaultPathVariable'
        default: 'defaultPathVariable'
        description: a variable defined with the server but used in the path
  - url:  https://{subdomainVariable}.test.com:{portVariable}/{firstPathVariable}/{secondPathVariable}
    description: relative server url
    variables:
      subdomainVariable: 
        enum:
          - defaultVariable 
          - nonDefaultVariable
        default: defaultVariable
        description: variable at start of server path
      portVariable:
        enum: 
          - '1234'
          - '5678'
        default: '1234'
        description: variable at end of server path, like port number
      firstPathVariable:
        enum: 
          - 'defaultFirstPathVariable'
          - 'nonDefaultFirstPathVariable'
        default: 'defaultPathVariable'
        description: a variable defined with the server but used in the path
      secondPathVariable:
        enum: 
          - 'defaultSecondPathVariable'
          - 'nonDefaultSecondPathVariable'
        default: 'defaultSecondPathVariable'
        description: a second path variable defined in the server URL
paths:
  /test/responseBody/string:
    get:
      responses:
        200:
          description: Response body should be a string
          content:
            application/json:
              schema:
                type: string
